---
- hosts: "localhost"
  connection: "local"
  vars:
    users:
    - "vasy"
    - "pety"
    - "masha"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "users"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
